version: "3.3"
services:
  search-api:
    build: .
    restart: always
    network_mode: "host"
    privileged: true
    container_name: search-api
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
        labels: "production_status"
        env: "os"
    labels:
      production_status: "testing"
    environment:
      - os=debian
    volumes:
      - /root/alpha-zero/searchAPI:/usr/src/app